name: Docker Nightly All Build
on:
#  push:
  schedule:
    - cron: '22 12 * * *'

jobs:
  nightly-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Set build date
        run: echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      -
        name: Set version
        run: echo "VERSION_TAG=nightly" >> $GITHUB_ENV

      -
        name: Build and push - default
        uses: docker/build-push-action@v4
        with:
          push: true
          target: default
          build-args: BUILD_DATE=${{ env.BUILD_DATE }},VERSION_TAG=${{ env.VERSION_TAG }}
          tags: atinoda/text-generation-webui:default-nightly

      -
        name: Build and push - cuda
        uses: docker/build-push-action@v4
        with:
          push: true
          target: cuda
          build-args: BUILD_DATE=${{ env.BUILD_DATE }},VERSION_TAG=${{ env.VERSION_TAG }}
          tags: atinoda/text-generation-webui:cuda-nightly

      -
        name: Build and push - triton
        uses: docker/build-push-action@v4
        with:
          push: true
          target: triton
          build-args: BUILD_DATE=${{ env.BUILD_DATE }},VERSION_TAG=${{ env.VERSION_TAG }}
          tags: atinoda/text-generation-webui:triton-nightly

      -
        name: Build and push - monkey-patch
        uses: docker/build-push-action@v4
        with:
          push: true
          target: monkey-patch
          build-args: BUILD_DATE=${{ env.BUILD_DATE }},VERSION_TAG=${{ env.VERSION_TAG }}
          tags: atinoda/text-generation-webui:monkey-patch-nightly

      -
        name: Build and push - llama-cpu
        uses: docker/build-push-action@v4
        with:
          push: true
          target: llama-cpu
          build-args: BUILD_DATE=${{ env.BUILD_DATE }},VERSION_TAG=${{ env.VERSION_TAG }}
          tags: atinoda/text-generation-webui:llama-cpu-nightly          
